languageCode = "en"
languageName = "English"
weight = 1
title = "Portable My Room"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/room.png"
  description = "Nana's blog"

[params.author]
  name = "Nana"
  email = ""
  image = "img/author_icon.jpeg"
  headline = "－Portable My Room－"
  bio = "何者でもない"
  #links = [
  #  { x-twitter = "https://twitter.com/burufugu" },
  #  { github = "https://github.com/nunocoracao/blowfish" },
  #]