languageCode = "en"
languageName = "English"
weight = 1
title = "Portable Room"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
#  logo = "img/author.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Nana"
  email = ""
  image = "img/author.png"
  headline = "－Portable Room－"
  bio = ""
  #links = [
  #  { x-twitter = "https://twitter.com/burufugu" },
  #  { github = "https://github.com/nunocoracao/blowfish" },
  #]